services:
  web:
    build: .
    ports: ["3000:3000"]
    depends_on: [db, redis]
    env_file: .env
    command: bin/rails server -b 0.0.0.0

  worker:
    build: .
    depends_on: [db, redis]
    env_file: .env
    command: bin/jobs

  git:
    build: .
    depends_on: [db]
    env_file: .env
    command: bin/rails git:server
    ports: ["2222:2222"]

  db:
    image: postgres:16
    volumes: ["postgres_data:/var/lib/postgresql/data"]
    environment:
      POSTGRES_PASSWORD: wokku

  redis:
    image: redis:7
    volumes: ["redis_data:/data"]

volumes:
  postgres_data:
  redis_data:
