# name: Spring Boot
# documentation: https://github.com/spring-guides/gs-spring-boot
# slogan: Java framework for production-grade applications
# category: frameworks
# tags: java, spring, api
# icon: java
# port: 8080

services:
  spring_boot:
    image: spring-boot:latest
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
