require "test_helper"

class Git::AuthorizedKeysWriterTest < ActiveSupport::TestCase
  setup do
    @user = users(:one)
    @key1 = @user.ssh_public_keys.create!(
      name: "laptop",
      public_key: "ssh-ed25519 AAAAFIRST user@host",
      fingerprint: "SHA256:#{SecureRandom.hex(8)}"
    )
    @key2 = @user.ssh_public_keys.create!(
      name: "desktop",
      public_key: "ssh-ed25519 AAAASECOND user@desk",
      fingerprint: "SHA256:#{SecureRandom.hex(8)}"
    )
  end

  test "render includes a banner" do
    assert_match(/AUTOGENERATED BY Git::AuthorizedKeysWriter/, Git::AuthorizedKeysWriter.render)
  end

  test "render emits one line per key with forced command + key id environment" do
    out = Git::AuthorizedKeysWriter.render

    assert_match(%r{command="/opt/wokku/bin/wokku-git-shell"}, out)
    assert_match(/no-pty/, out)
    assert_match(/no-port-forwarding/, out)
    assert_match(/environment="WOKKU_GIT_KEY_ID=#{@key1.id}"/, out)
    assert_match(/environment="WOKKU_GIT_KEY_ID=#{@key2.id}"/, out)
    assert_match(/ssh-ed25519 AAAAFIRST/, out)
    assert_match(/ssh-ed25519 AAAASECOND/, out)
  end

  test "render strips whitespace-only noise from stored pubkeys" do
    key = @user.ssh_public_keys.create!(
      name: "messy", public_key: "  ssh-ed25519   AAAAMESSY  user@h\n",
      fingerprint: "SHA256:#{SecureRandom.hex(8)}"
    )
    line = Git::AuthorizedKeysWriter.render(scope: SshPublicKey.where(id: key.id))
    assert_match(/ssh-ed25519 AAAAMESSY user@h$/, line.strip)
    refute_match(/\n\s+ssh/, line) # no embedded newlines before the key
  end

  test "write! no-ops when no path configured" do
    ENV.delete("WOKKU_GIT_AUTHORIZED_KEYS_PATH")
    assert_nil Git::AuthorizedKeysWriter.write!
  end

  test "write! writes content atomically when path is configured" do
    Dir.mktmpdir do |dir|
      path = File.join(dir, "sub", "authorized_keys")
      result = Git::AuthorizedKeysWriter.write!(path: path)
      assert_equal path, result
      assert File.exist?(path)
      assert_match(/ssh-ed25519 AAAAFIRST/, File.read(path))
      assert_equal 0o600, File.stat(path).mode & 0o777
    end
  end

  test "write! is idempotent" do
    Dir.mktmpdir do |dir|
      path = File.join(dir, "authorized_keys")
      Git::AuthorizedKeysWriter.write!(path: path)
      first_content = File.read(path)
      Git::AuthorizedKeysWriter.write!(path: path)
      assert_equal first_content, File.read(path)
    end
  end
end
