require "openssl"
require "fileutils"

module Git
  # Builds the authorized_keys file that sshd reads for the `git` user on
  # the wokku.cloud host, from every row in the ssh_public_keys table.
  #
  # Each SshPublicKey becomes one line:
  #
  #   command="/opt/wokku/bin/wokku-git-shell",no-pty,no-port-forwarding,
  #           no-agent-forwarding,no-X11-forwarding,no-user-rc,
  #           environment="WOKKU_GIT_KEY_ID=<id>" ssh-ed25519 AAAAC3... user@host
  #
  # The only part the user contributes is the final pubkey material,
  # authenticated cryptographically by sshd. WOKKU_GIT_KEY_ID is set by
  # us, not the client — the gateway trusts it as the authoritative
  # identity of the connecting key.
  #
  # Typical use:
  #
  #   Git::AuthorizedKeysWriter.write!
  #
  # Writes to the path from WOKKU_GIT_AUTHORIZED_KEYS_PATH (defaults to
  # "/etc/wokku/git-authorized-keys"). If the env var is unset in the
  # current environment (e.g. dev/test), .write! is a no-op — we don't
  # want a developer running tests to clobber a real prod file.
  class AuthorizedKeysWriter
    DEFAULT_PATH   = "/etc/wokku/git-authorized-keys"
    FORCE_COMMAND  = "/opt/wokku/bin/wokku-git-shell"
    COMMAND_OPTS   = %w[no-pty no-port-forwarding no-agent-forwarding no-X11-forwarding no-user-rc].freeze

    class << self
      # Write the authorized_keys file to disk. Returns the path written,
      # or nil if writing was skipped.
      def write!(path: configured_path, force: false)
        return nil if path.blank? && !force
        path ||= DEFAULT_PATH

        FileUtils.mkdir_p(File.dirname(path))
        content = render

        # Atomic replace to avoid sshd reading a half-written file.
        tmp = "#{path}.tmp.#{Process.pid}"
        File.open(tmp, "w", 0o600) { |f| f.write(content) }
        File.rename(tmp, path)
        path
      end

      # The generated file content as a string (useful for rake/debug +
      # for tests).
      def render(scope: SshPublicKey.all)
        lines = scope.order(:id).map { |key| line_for(key) }
        ([ banner ] + lines).join("\n") + "\n"
      end

      # Path to write. Derived from ENV; blank in dev/test so we don't
      # accidentally clobber anything.
      def configured_path
        ENV["WOKKU_GIT_AUTHORIZED_KEYS_PATH"].presence
      end

      private

      def banner
        <<~TXT.strip
          # AUTOGENERATED BY Git::AuthorizedKeysWriter — DO NOT EDIT BY HAND
          # Regenerated whenever an SshPublicKey row is inserted or deleted.
          # Rewrite at will via `bin/rails wokku:gateway:write_authorized_keys`.
        TXT
      end

      def line_for(key)
        opts = [
          %(command="#{FORCE_COMMAND}"),
          *COMMAND_OPTS,
          %(environment="WOKKU_GIT_KEY_ID=#{key.id}")
        ].join(",")

        # Strip any trailing newlines/whitespace in the stored pubkey
        # before splicing.
        pubkey = key.public_key.to_s.strip.gsub(/\s+/, " ")
        "#{opts} #{pubkey}"
      end
    end
  end
end
