# documentation: https://github.com/saleor/saleor
# slogan: GraphQL-first e-commerce platform
# category: ecommerce
# tags: ecommerce, graphql, python
# icon: ecommerce

services:
  saleor:
    image: saleor:latest
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7

volumes:
  postgres-data:
