# name: Portainer
# documentation: https://github.com/portainer/portainer
# slogan: Lightweight management UI for Docker environments
# category: developer-tools
# tags: docker, containers, management, devops
# icon: developer-tools
# port: 9000

services:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  portainer-data:
