service: wokku
image: johannesdwicahyo/wokku

servers:
  web:
    hosts:
      - 43.159.57.11

proxy:
  ssl: true
  host: wokku.dev

registry:
  server: localhost:5000
  username: _
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - WOKKU_DATABASE_PASSWORD
    - RESEND_API_KEY
    - SENTRY_DSN
  clear:
    SOLID_QUEUE_IN_PUMA: true
    DB_HOST: wokku-db
    REDIS_URL: redis://wokku-redis:6379/0
    RAILS_LOG_LEVEL: info
    WEB_CONCURRENCY: 2
    IPAYMU_VA: "0000001914914286"
    IPAYMU_API_KEY: "SANDBOX2BAE12F9-82A3-49CA-B1B2-6BF9ACD0D8A9"
    IPAYMU_URL: "https://sandbox.ipaymu.com"
    APP_URL: "https://wokku.dev"

volumes:
  - "wokku_storage:/rails/storage"

asset_path: /rails/public/assets

ssh:
  user: deploy

builder:
  remote: ssh://deploy@43.159.57.11
  arch: amd64
  secrets:
    - WOKKU_EE_TOKEN

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

accessories:
  db:
    image: postgres:16
    host: 43.159.57.11
    port: "127.0.0.1:5432:5432"
    env:
      clear:
        POSTGRES_USER: wokku
        POSTGRES_DB: wokku_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - wokku_postgres_data:/var/lib/postgresql/data
    options:
      network: "kamal"
  redis:
    image: redis:7
    host: 43.159.57.11
    port: "127.0.0.1:6379:6379"
    directories:
      - wokku_redis_data:/data
    cmd: redis-server --appendonly yes --maxmemory 128mb --maxmemory-policy allkeys-lru
    options:
      network: "kamal"
