service: wokku
image: johannesdwicahyo/wokku

servers:
  web:
    - 43.159.57.11
    options:
      network: "kamal"

proxy:
  ssl: true
  host: wokku.dev

registry:
  server: ghcr.io
  username: johannesdwicahyo
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - WOKKU_DATABASE_PASSWORD
  clear:
    SOLID_QUEUE_IN_PUMA: true
    DB_HOST: wokku-db
    REDIS_URL: redis://wokku-redis:6379/0
    RAILS_LOG_LEVEL: info
    WEB_CONCURRENCY: 2

volumes:
  - "wokku_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

accessories:
  db:
    image: postgres:16
    host: 43.159.57.11
    port: "127.0.0.1:5432:5432"
    env:
      clear:
        POSTGRES_USER: wokku
        POSTGRES_DB: wokku_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - wokku_postgres_data:/var/lib/postgresql/data
    options:
      network: "kamal"
  redis:
    image: redis:7
    host: 43.159.57.11
    port: "127.0.0.1:6379:6379"
    directories:
      - wokku_redis_data:/data
    cmd: redis-server --appendonly yes --maxmemory 128mb --maxmemory-policy allkeys-lru
    options:
      network: "kamal"
