# name: Strapi
# documentation: https://github.com/strapi/strapi
# slogan: Leading open-source headless CMS
# category: cms
# tags: headless-cms, api, node
# icon: cms
# port: 1337

services:
  strapi:
    image: strapi/strapi:latest
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
